### ISSUE TITLE
As SRE, I want to create a CI to automate builds and tests 

### ISSUE THREAD

**Issue by ThomasCardin** [ClubCedille/calidum-rotae#45]
- Automate Test
- Automate builds of the microservices
- Lint (maybe)
- ...

**Comment by SonOfLope** [comment]
Commentaire de cguertin14 deplacer ici : 
### Also add badges in the README

* Go code quality -> https://goreportcard.com/report/github.com/clubcedille/calidum-rotae-backend
* Go code coverage -> https://about.codecov.io/
* Docker image badge for downloads

Should look like this:
![image](https://user-images.githubusercontent.com/23645771/167047618-9bfe45a7-61df-41b6-b638-c9371a9837e4.png)
